### PR TITLE
Adding append_slash option to Hammock

### PR DESCRIPTION
**Pull request by maraujop**
Adds a flag to add an slash to the url, this is necessary for some APIs, defaults to `False` for backwards compatibility.

Cheers,
Miguel

### CODE REVIEW

**Comment by rubik** [comment]
+1 on this. Very useful to me.

**Comment by kadirpekel** [comment]
Hi guys, my opinion is a bit different. How you find the way #7 ?

**Comment by maraujop** [comment]
Hi @kadirpekel ,

I've read your implementation and to me it seems harder to follow, it's more magical. You are already passing some parameters to `Hammock` constructors in `__iter__` and `__getattr__`, I'm referring to `name` and `parent`, so why not following the same approach for `append_slash`?

What I like, is that in `_url` my conditionals are too complicated, there is no need for an `if else` as I've done. I could rebase that if you want me to.

Also I think you should have a look at PR #5, because it's a little bit related to what you proposed PR (The fact of traversing hammocks for grabbing attributes).

Cheers,
Miguel

**Comment by rubik** [comment]
To me both of the implementations are good. What I like of @kadirpekel's implementation is that it follows the same approach of `_probe_session`. Maybe I'd rewrite that using `any()` which short-circuit, while `reduce()` does not. Something on the lines of:

```
any(hammock._append_slash for hammock in self)
```

I don't find it too magical, since it is just iterating over itself calling `__iter__`.

**Comment by maraujop** [comment]
I will try to rephrase previous comment and again this is related to #5.

I agree both implementations are legit and @kadirpekel is following the same approach that in `_probe_session`, which is good and more consistent, you are right @rubik .

If I'm not mistaken it doesn't really matter that `reduce` doesn't short-circuit, because you will always have to traverse to the root, because that's the only one that can have a flagged `append_slash`, right?

But I will try to explain what I think is wrong in this approach. If I'm subclassing Hammock, which now needs #5 to work correctly, and I set some extra attribute in my constructor, let's say I do `self._testing = True`, then I will have to write a method for traversing hammock, to find that value.

So that's why I proposed #5, which is subsequent to this pull request and would remove the necessity of passing `append_slash` in `__iter__` and `__getattr__` and also would remove the necessity of traversing for getting session in `_probe_session`.  This way people can easily subclass `Hammock` and you are not forced to know and understand how internals work. 

Also beware that functional programming with an `__iter__` method is not basic Python and some people would feel it looks magical, that's what I meant. I'm a big fan of functional programming myself.

Cheers,
Miguel

**Comment by rubik** [comment]
Ah I see now. I had not considered #5 before. Well if #5 get accepted then, as you say, it would be much easier to to this. So, let's see what happens to #5..

**Comment by kadirpekel** [comment]
Miguel's arguments seem reasonable. Although Hammock reveals some magic, it also must able to be extended properly. So we must maintain the balance. Beside these i'm trying to keep Hammock as simple as it could be.

Gonna review #5 asap and hopefully we could take Hammock one step further together with your kind helps. Thank you all.

**Comment by rubik** [comment]
> Beside these i'm trying to keep Hammock as simple as it could be.

Yes, I think this is a very important point here. First time I saw Hammock I was blown away by its power and yet its semplicity.

**Comment by kadirpekel** [comment]
Ok guys, how about this one #8. I think (I hope), it solves almost all issues experimentally we discuss. But, i'd better do a concrete subclassing example to see if it really works though all unit tests passed.

**Comment by maraujop** [comment]
I've commented it there.

**Comment by kadirpekel** [comment]
Fixed by #8

**Pull request closed without merging**
