### PR TITLE
instead of probing attributes for ascendants, shallow copy technique use...

### PR DESCRIPTION
**Pull request by kadirpekel**
...d for generating child hammock instances

### CODE REVIEW

**Comment by maraujop** [comment]
@kadirpekel 

You've totally grokked what I meant in previous comments of PR #4 and what my code does in PR #5.

As I said this simplifies some methods, because there is no need to traverse, that you've removed. This makes in my opinion Hammock simpler, which is your objective and mine :D

I really like your solution of using shallow copy for maintaining previous values persisted without hitting performance so much. It's way more elegant than my iteration over `__dict__` for persisting attributes, It's now me who feels embarrassed :)

It also fixes the problem of returning a subclass of Hammock, because you start copying the "root" of the tree and my test case makes sure of both problems.

+1 for merging this in, well done!

There is one thing I'm not sure I follow:

``` python
if name.startswith('__'):
    raise AttributeError(name)
```

What is this for?

Cheers,
Miguel

**Comment by rubik** [comment]
I am +1 on this too. I find this implementation is totally great!

@maraujop: That means that you cannot add a path component starting with double underscore. Since no reasonable REST API has components starting with double underscore that's safe. And if you try `Hammock.__dict__` it still works, since `__getattr__` is called after `__getattribute__`, i.e. when an attribute is not found. But is that check even needed?

**Comment by maraujop** [comment]
@rubik Yeah, well, that's what it looked like, but I was wondering the same as you, is it really necessary?

**Comment by kadirpekel** [comment]
Thank you @maraujop and @rubik for kind words. You know that is which we try to make something simple, robust and useful together. Implementation can be improved always anytime, the important one is the such nice ideas just like the ones you suggest. So there is no reason for embarrassing ;)

The underscore guard you mentioned is the check i had to put as a workaround since `copy` implementation somehow requests some hidden (__) attributes that is not found on Hammock instance which causes an infinite loop. If you have deeper understandings with this, i'm open for yet another workaround.

If we agreed, i'm gonna merge this asap with a new release published on pypi.

Enjoy.

**Comment by kadirpekel** [comment]
Btw, I utilized the suggestions at http://www.peterbe.com/plog/must__deepcopy__

Maybe it helps.

**Comment by maraujop** [comment]
> The underscore guard you mentioned is the check i had to put as a workaround since copy implementation somehow requests some hidden (__) attributes that is not found on Hammock instance which causes an infinite loop. If you have deeper understandings with this, i'm open for yet another workaround.

I see, It makes sense. How about adding a little inline comment saying `# Avoids infinite loops when shallow copying`.

This reduces my PRs to one, the one that is probably going to be rejected :)

Cheers,
Miguel

**Comment by rubik** [comment]
Here is the problem:
http://hg.python.org/cpython/file/82ae284cd5f1/Lib/copy.py#l89

when `reductor(2)` is called it get stuck...

**Comment by rubik** [comment]
There you go! Found it! Just add a `__reduce__` method:

```
def __reduce__(self):
    return (self.__class__, tuple(mock._name for name in self))
```

If you do this that check is no more needed and `Hammock` should be `copy`able and `pickle`able as well.

**Comment by kadirpekel** [comment]
Guys, thank you very much, without your support, there wouldn't be Hammock 0.2.0 http://pypi.python.org/pypi/hammock

**Comment by rubik** [comment]
Glad to help. @kadirpekel: do you think is it worth adding another method?

**Comment by kadirpekel** [comment]
Sorrry :( What you mean by "adding another method". Could not get it.

**Comment by kadirpekel** [comment]
Ooops! Haven't seen @rubik's latest comment. Oh, looking into it, sorry...

**Comment by kadirpekel** [comment]
Is implementing `__reduce__` method has more advantages than explicitly ignoring all double underscored special methods? Also if choose implementing `__reduce__`, what about the `__reduce_ext__` one. Hmmm, i'm in doubt but i think my vote goes for the current explicit one. What you think, is it worth to implement `__reduce__`?

**Comment by rubik** [comment]
Well if you want Hammock to be pickleable, then the `__reduce__` method is definitely required. Probably it's not a common need to pickle an Hammock instance, still, the current implementation is a hack. If you choose to implement `__reduce__` then you do not need to worry about `__reduce_ex__`, since the latter was introduced to make the implementation aware of the protocols. I don't think in this case it would be required.
So to implement it or not, you should decide, since you're the chief here. ;)
If you prefer to leave it simple as it is now,  it's ok for me!

**Comment by maraujop** [comment]
It's good to know what was going on @rubik, thanks for finding that out and explaining it, you learn something everyday.

I honestly don't have an strong opinion on which path to take. I don't see myself pickling Hammock. But the way it's controlled now feels a little hacky, while `__reduce__` is what Python wants you to implement for avoiding this kind of problem. 

Anyway, If the current check stays, that would be a good line of code for an inline comment as I stated before, because it's not evident why it's there for new comers.

BTW @kadirpekel don't forget to add `append_slash` to the README and you might consider adding a changelog to Hammock. I remember when i started releasing some apps I never did it and now I regret it.

Cheers,
Miguel

**Comment by kadirpekel** [comment]
Hi guys, i had a detailed look at `__reduce__` interface, but as far as i understand we have to keep state of constructor  paramaters and return them within `__reduce__`  as a tuple also with `__class__` reference. I think choosing this way is complex and also hard, not simple as @rubik' s pseudo example.

@rubik Have you got comparatively simple `__reduce__` implementation? If so, if you mind sending a PR, it could help us to decide and proceed.

@maraujop: Yeah i know Miguel, we have to maintain a changelog, PEP8 conventions and a detailed documentation. Hmmm, i'm yet trying my best to allocate some time to Hammock :) Don't worry, i'm aware of these issues, gonna overcome ;)

Also, spreading words about hammock is a very good idea, you' re good to leave any reference about Hammock anywhere. 

Your help is appreciated very much, thank you all.

**Comment by rubik** [comment]
@kadirpekel: Well that's roughly what the above implementation does. It returns a tuple which pickle and/or copy will use to reconstruct the object. The state is kept by return the necessary parameters. To keep perfect state you will have to return the `_parent`, `_append_slash` and `_session` parameters as well.
I think this would do the job:

```
def __reduce__(self):
    return (self.__class__, (self._name, self._parent, self._append_slash),
            {'_session': self._session})

def __setstate__(self, state):  # not sure how to implement this one
    self.__dict__.update(state)
```

This would support both `copy` and `pickle`. But since most of the time `_session` is a module and you cannot pickle modules, this would not make much sense. Therefore, I would opt for the `__copy__` method alone, which would support only `copy` (draft):

```
def __copy__(self):
    cop = self.__class__(self._name, self._parent, self._append_slash)
    cop._session = self._session
    return cop
```

**Comment by maraujop** [comment]
@kadirpekel :D I will try to help you out with it. I don't mind doing it, i just wanted to remind it to you. Also, you have my word about recommending Hammock to anyone I know :)

@rubik Beware Michele, that if we do it your way, only `name`, `parent`, `append_slash` and `session` would be kept when shallow copying (chaining). So if you subclass Hammock and define a `self.testing` variable that you use in an overridden or custom method, that would be lost.

Actually your `__copy__` code looks similar to my PR #5, but without iterating over `__dict__` for setting extra attributes. So it looks like, if we do it this way, we would end up having to do something as I was doing in the beginning and that feels a little more complex and hacky. Does it make sense?

Cheers,
Miguel

**Comment by rubik** [comment]
Yeah, totally agree. At this point it would become just too complex, let's keep it like it is now...

**Pull request merged**
