### PR TITLE
PEP 8 fixes to Hammock!

### PR DESCRIPTION
**Pull request by rubik**
Just some PEP 8. And btw, thanks for this amazing module! Really awesome!

Another thing: why a package containing only an `__init__.py`? It makes no sense to me.
Why not convert it to a module (`hammock.py`) and changing `packages=['hammock']` to `py_modules=['hammock']` in `setup.py`? I can easily add another commit so that you can just accept the request.

### CODE REVIEW

**Comment by kadirpekel** [comment]
That's great. Thank you for reminding those lovely PEP8 conventions ;) I must use a lint tool though :)

**Comment by rubik** [comment]
I always use pep8, autopep8 and pylint. They're great tools! :)
And what about the package to module?

**Comment by kadirpekel** [comment]
What is the actual advantage with converting package to module setup? If something reasonable, let's do it but AFAIK, general distribution convention is to just declare it as a package.

**Comment by rubik** [comment]
Well a package is a collection of modules and there is no module in hammock/, except `__init__.py` which should be used for initialization. There is no such convention AFAIK. From the setuptools point of view: if you only declare a module it will simply copied in the PYTHONPATH, on the other hand installing a package is more laborious. I don't know if there are any practical advantages, but my opinion is that if we need a module why creating a package?

**Comment by kadirpekel** [comment]
I see, i have no objections though. I agree with the weirdness of the placement of actual module code such accessing it through `__init__.py`. Since it would be better to settle it to the root of the project as `hammock.py`, let's do it then :)

**Comment by rubik** [comment]
Great! I'm glad we agree! ;)
I'm opening another pull request, it should be very simple.

**Pull request merged**
