### PR TITLE
Allow for ignored components

### PR DESCRIPTION
**Pull request by caruccio**
Hi, this is a patch that allows to strip out specific uri components passed to **call**().
This is util where non-validated data is used to build some url but it is ok if missing.

Silly example:

<pre>
 >>> h=hammock.Hammock('http://url.com', ignore=(False,None))
 >>> h.goodbye(True, False).cruel(None).world.False
 http://url.com/goodbye/True/cruel/world/False
</pre>

### CODE REVIEW

**Comment by kadirpekel** [comment]
Hi Mateus,

Sorry for late reply, but honestly i could not understand the purpose of this feature request. Could you please elaborate on this? Why do you want to add such a feature, any practical use case do you have?

In my opinion, ignoring values those not evaluate to 'True' might automatically be omitted, maybe. But giving an ignorant list explicitly is not an elegant way to choose i think.

**Comment by rubik** [comment]
I suggest that for these kind of uses you subclass the `Hammock` class and add your desired functionality. This way the base class still remains flexible.

**Comment by caruccio** [comment]
Hello Kadir,

Sometimes I am too lazy to validate parameters.
Since "ignore" applies only to parameterized components, it's easy to discard "dynamic" invalid values.

I got this idea when writing this bottle handler (or something like this):

```
@get("/user/<name>/<phone>")
def get_user(name, phone=None):
    api = hammock.Hammock('http://my-backend-rest-api', ignore=(None))
    return api.user(name, phone).GET()
```

Otherwise I'd have to check if 'phone' is valid prior to call GET:

```
if phone is None:
    return api.user(name).GET()
else:
    return api.user(name, phone).GET()
```

Ignoring values those not evaluate to 'True' may not be a good approach. You can't known if some non-True component is valid or not. For instance, "/path/False/0/" is an entirely legitimate URI.

Maybe it is not a fancy feature, but saves some keystrokes ;)

@rubik, the base class still flexible since "ignore" is optional.

Thanks for feedback.

**Comment by kadirpekel** [comment]
Oh yes, i see, the '0' example shows that mine was a bad idea but it still might be reasonable ignoring only 'None' values. Anyway, it should be discussed, i don't have strong feelings about though.

My individual preference is not to merge this request since it does not seem reasonable enough to me because I want to keep hammock as minimal and natural as it can be.

**Pull request closed without merging**
